In [ ]:
from sgkit_plink import pysnptools
import xarray as xr
import imp
imp.reload(pysnptools)

In [7]:
ds = pysnptools.read_plink('/tmp/plink_sim_10s_100v_10pmiss', bim_sep='\t', fam_sep='\t', bim_int_contig=True)
ds

<xarray.Dataset>
Dimensions:             (alleles: 2, ploidy: 2, samples: 10, variants: 100)
Dimensions without coordinates: alleles, ploidy, samples, variants
Data variables:
    variant/contig      (variants) int16 dask.array<chunksize=(100,), meta=np.ndarray>
    variant/position    (variants) int32 dask.array<chunksize=(100,), meta=np.ndarray>
    variant/alleles     (variants, alleles) |S1 dask.array<chunksize=(100, 1), meta=np.ndarray>
    sample/id           (samples) <U1 dask.array<chunksize=(10,), meta=np.ndarray>
    call/genotype       (variants, samples, ploidy) int8 dask.array<chunksize=(100, 10, 2), meta=np.ndarray>
    call/genotype_mask  (variants, samples, ploidy) bool dask.array<chunksize=(100, 10, 2), meta=np.ndarray>
    variant/id          (variants) <U1 dask.array<chunksize=(100,), meta=np.ndarray>
    sample/family_id    (samples) <U1 dask.array<chunksize=(10,), meta=np.ndarray>
    sample/member_id    (samples) <U1 dask.array<chunksize=(10,), meta=np.ndarray>
    sample/paternal_id  (samples) <U1 dask.array<chunksize=(10,), meta=np.ndarray>
    sample/maternal_id  (samples) <U1 dask.array<chunksize=(10,), meta=np.ndarray>
    sample/sex          (samples) int8 dask.array<chunksize=(10,), meta=np.ndarray>
    sample/phenotype    (samples) int8 dask.array<chunksize=(10,), meta=np.ndarray>
Attributes:
    contigs:  ['1']

In [8]:
ds['variant/contig'].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [5]:
ds['sample/sex'].values

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int8)

In [7]:
x = ds['call/genotype']

In [10]:
sample_call_rates = (ds['call/genotype'] >= 0).max(dim='ploidy').mean(dim='variants').values
sample_call_rates

array([0.95, 0.9 , 0.91, 0.87, 0.86, 0.83, 0.86, 0.87, 0.92, 0.92])

In [11]:
np.testing.assert_equal(sample_call_rates, [0.95, 0.9, 0.91, 0.87, 0.86, 0.83, 0.86, 0.87, 0.92, 0.92])

In [9]:
ds['call/genotype'].clip(0, 2).sum(dim='ploidy').sum(dim='variants').values

nan
True


array([102,  95,  98,  94,  88,  91,  90,  98,  96, 103])

In [ ]:
[102, 95, 98, 94, 88, 91, 90, 98, 96, 103]