In [5]:
from sgkit_plink import pysnptools
import xarray as xr
import numpy as np
from pathlib import Path

PosixPath('/home/jovyan/work/repos/sgkit-plink/tests/data')

In [21]:
#path = Path(pysnptools.__file__).resolve().parents[1] / 'sgkit_plink' / 'tests' / 'data' / 'plink_sim_10s_100v_10pmiss'
path = '/tmp/plink_sim_10s_100v_10pmiss'
ds = pysnptools.read_plink(path=path, bim_sep='\t', fam_sep='\t', bim_int_contig=True)
ds

<xarray.Dataset>
Dimensions:             (alleles: 2, ploidy: 2, samples: 10, variants: 100)
Dimensions without coordinates: alleles, ploidy, samples, variants
Data variables:
    variant_contig      (variants) int16 dask.array<chunksize=(100,), meta=np.ndarray>
    variant_position    (variants) int32 dask.array<chunksize=(100,), meta=np.ndarray>
    variant_allele      (variants, alleles) |S6 dask.array<chunksize=(100, 1), meta=np.ndarray>
    sample_id           (samples) <U3 dask.array<chunksize=(10,), meta=np.ndarray>
    call_genotype       (variants, samples, ploidy) int8 dask.array<chunksize=(100, 10, 2), meta=np.ndarray>
    call_genotype_mask  (variants, samples, ploidy) bool dask.array<chunksize=(100, 10, 2), meta=np.ndarray>
    variant_id          (variants) <U13 dask.array<chunksize=(100,), meta=np.ndarray>
    sample_family_id    (samples) <U1 dask.array<chunksize=(10,), meta=np.ndarray>
    sample_paternal_id  (samples) <U4 dask.array<chunksize=(10,), meta=np.ndarray>
    sample_maternal_id  (samples) <U4 dask.array<chunksize=(10,), meta=np.ndarray>
    sample_sex          (samples) int8 dask.array<chunksize=(10,), meta=np.ndarray>
    sample_phenotype    (samples) int8 dask.array<chunksize=(10,), meta=np.ndarray>
Attributes:
    contigs:  ['1']

In [36]:
slices = (slice(1, 2), slice(0, 1))
np.array([[1,2],[3,4]])[slices]

array([[3]])

In [4]:
ds['variant/contig'].values

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [5]:
ds['sample/sex'].values

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1], dtype=int8)

In [43]:
np.random.seed(1)
gt = ds['call/genotype'].values
idx = np.array(list(np.ndindex(gt.shape[:2])))
idx = idx[np.random.choice(np.arange(idx.shape[0]), size=10, replace=False)]
gt[tuple(idx.T)].shape, idx.shape

((10, 2), (10, 2))

In [44]:
idx

array([[50,  7],
       [81,  8],
       [45,  2],
       [36,  8],
       [24,  2],
       [92,  9],
       [26,  2],
       [81,  0],
       [31,  8],
       [ 4,  9]])

In [45]:
np.stack([
    gt[50, 7],
    gt[45, 2],
    gt[24, 2]
])

array([[ 1,  0],
       [ 1,  1],
       [-1, -1]])

In [47]:
gt[tuple(idx.T)]

array([[ 1,  0],
       [ 1,  0],
       [ 1,  1],
       [ 1,  1],
       [-1, -1],
       [ 0,  0],
       [ 0,  0],
       [ 1,  1],
       [ 0,  0],
       [ 0,  0]])

In [10]:
sample_call_rates = (ds['call/genotype'] >= 0).max(dim='ploidy').mean(dim='variants').values
sample_call_rates

array([0.95, 0.9 , 0.91, 0.87, 0.86, 0.83, 0.86, 0.87, 0.92, 0.92])

In [9]:
ds['call/genotype'].clip(0, 2).sum(dim='ploidy').sum(dim='variants').values

nan
True


array([102,  95,  98,  94,  88,  91,  90,  98,  96, 103])

In [ ]:
ds.assign(ds[['call_genotype', 'variant_id']])